### ISSUE TITLE
closed issue

### ISSUE THREAD

**Issue by easycashsniper** [sai-krishna-msk/Customer_Anylatics#1]
Hi,

Thank you for the answer

**Comment by sai-krishna-msk** [comment]
> Hi,
> 
> This is very interesting, do you have any idea about how to extend the study on a case with larger dataset containing hundreds of brands and items ?

I don't think the underlying method would change rather you would be writing scripts(functions) to generate results at scale  rather than doing them in Jupiter notebook.

@easycashsniper

**Comment by easycashsniper** [comment]
Thank you for your answer but here's what's bothering me tactically : In the proposed approach the dataset contain a column for each price and promotion, it would not be possible to create a dataset with 100.000 columns that refer to all products prices and promotions
